%% SIMULATION PARAMETERS
TIME_STEP = 64;

%% ROBOT PARAMETERS
ROBOT_NAME = 'TableUV';
ROBOT_BASE_RADIUS = 0.03;
WHEEL_RADIUS = 0.017;

TABLE_WIDTH = 1.22;
TABLE_HEIGHT = 0.76;

MAX_SPEED = 6.28;

%% SENSOR PARAMETERS
% ENCODER 
ENC_RESOLUTION = -1;
ENC_NOISE = -1;

% IMU_GYRO
IMU_GYRO_RESOLUTION = -1;
IMU_GYRO_NOISE = -1;

% IMU_ACC
IMU_ACC_RESOLUTION = -1;